import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Side_Bar from "@/components/side-bar/page";
import JotaiProviderWrapper from "./JotaiProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}antialiased flex md:flex-row flex-col-reverse gap-10 bg-[#F5F5F5]`}
      >
        <Side_Bar />
        <JotaiProviderWrapper>{children}</JotaiProviderWrapper>
      </body>
    </html>
  );
}
